export const SHAPE_LOGO_INTRO_TIMING = {
  LETTER_DURATION: 0.72,
  LETTER_STAGGER: 0.32,
  SUBTITLE_DELAY: 1.95,
  SUBTITLE_DURATION: 3.0,
  CONTENT_DELAY: 4.3,
  CONTENT_STAGGER: 0.12,
} as const;

export const SHAPE_LOGO_INTRO_EASE = [0.22, 1, 0.36, 1] as const;

export const SHAPE_LOGO_LETTER_DELAYS = [
  0,
  SHAPE_LOGO_INTRO_TIMING.LETTER_STAGGER,
  SHAPE_LOGO_INTRO_TIMING.LETTER_STAGGER * 2,
  SHAPE_LOGO_INTRO_TIMING.LETTER_STAGGER * 3,
  SHAPE_LOGO_INTRO_TIMING.LETTER_STAGGER * 4,
] as const;
